import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/custom/layouts/theme-provider";
import { Inter } from "next/font/google";

// Subsets are really important. CHECK BELOW FOR MORE INFO
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
